### ISSUE TITLE
There are duplicates heroes in the dropdown in the player comparison tool

### ISSUE THREAD

**Issue by crorella** [hotsdata/hotsdata-frontend#7]
For example, ETC and E.T.C., Diablo is there twice, etc.

**Comment by ayrock-dev** [comment]
Is this something we want to handle api-side, or on the frontend. I can filter the set to look for an alias on the frontend - Aka E.T.C. would find an alias to ETC - but this might be something the api might want to do. I assume this is caused by a change in replay data at some point?

**Comment by crorella** [comment]
Good point, @ayrock-dev, I think the root cause is related with a bug in [heroesinfo](https://github.com/hotsdata/heroesinfo) where the internal name of the hero (in this case ETC) is not being translated correctly into the 'friendly name' of the hero (in this case E.T.C.), which creates a new record in the table used by the API.

But there is also another case where the same value is present twice (Diablo, for example), for this case I don't know if the issue is with the query used by the API or with heroesinfo or even the table. I will investigate today.

**Comment by crorella** [comment]
After checking the endpoint used by the front end, the SQL query used by the API and the table referenced in the SQL I think the problem is caused by several things:

- The way the table is designed is to keep several copies of the heroes, one per patch.
- The SQL used by the API is just selecting hero name and hero role, not filtering by any particular patch, so many records per hero are retrieved.
- heroesinfo is not doing a good job at mapping internal hero names to the actual hero names.

For now, something we can do is to clean the hero table and update the hero names. Also I would like to change the structure and just keep one version of the hero regardless of the patch version.

**Comment by crorella** [comment]
I just fixed the table, here are the commands I used:

```
create table heroes_v2
(
	id varchar(64) PRIMARY KEY not null,
	patch integer not null,
	name varchar(64),
	role varchar(64),
	universe varchar(64),
	alignment varchar(64),
	rarity varchar(64),
	portrait_icon varchar(128),
	gender varchar(64),
	difficulty varchar(64),
	damage smallint,
	utility smallint,
	complexity smallint,
	survivability smallint,
	attrib_name varchar(10)
);

DELETE FROM heroes WHERE
name IN ('AI', '_Empty', 'LegacyVOHero', 'Missing', 'Random', 'TestHero')
AND patch = 57547

UPDATE heroes set name = 'Li Li' WHERE name = 'LiLi';
UPDATE heroes set name = 'E.T.C.' WHERE name = 'ETC';

INSERT INTO heroes_v2
SELECT
  id,
  MIN(patch) AS patch,
  name,
  MAX(role) AS role,
  MAX(universe) AS universe,
  MAX(alignment) AS alignment,
  MAX(rarity) AS rarity,
  MAX(portrait_icon) AS portrait_icon,
  MAX(gender) AS gender,
  MAX(difficulty) AS difficulty,
  MAX(damage) AS damage,
  MAX(utility) AS utility,
  MAX(complexity) AS complexity,
  MAX(survivability) AS survivability,
  MAX(attrib_name) AS attrib_name
FROM heroes
GROUP BY id, name
ORDER BY id, name ASC;

alter table heroes rename to heroes_old;

alter table heroes_v2 rename to heroes;

```

**Comment by ayrock-dev** [comment]
Nice work @crorella. Fixing this on the data side was the right choice.
